import { Offer, Partner } from './types';

export const mockPartners: Partner[] = [
  {
    id: '1',
    user_id: '1',
    business_name: 'Bakery Sakartvelo',
    business_type: 'BAKERY',
    description: 'Traditional Georgian bakery serving fresh khachapuri and pastries daily',
    location: {
      address: '123 Rustaveli Avenue, Tbilisi',
      city: 'Tbilisi',
      coordinates: { lat: 41.7151, lng: 44.8271 },
    },
    contact: {
      phone: '+995 555 123 456',
      email: 'info@bakery-sakartvelo.ge',
      telegram: '@bakery_sakartvelo',
      whatsapp: '+995555123456',
    },
    business_hours: {
      monday: { open: '08:00', close: '20:00' },
      tuesday: { open: '08:00', close: '20:00' },
      wednesday: { open: '08:00', close: '20:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    status: 'APPROVED',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: '2',
    business_name: 'Café Aroma',
    business_type: 'CAFE',
    description: 'Cozy café with specialty coffee and homemade desserts',
    location: {
      address: '45 Chavchavadze Avenue, Tbilisi',
      city: 'Tbilisi',
      coordinates: { lat: 41.7089, lng: 44.7739 },
    },
    contact: {
      phone: '+995 555 234 567',
      email: 'hello@cafe-aroma.ge',
    },
    business_hours: {
      monday: { open: '07:00', close: '22:00' },
      tuesday: { open: '07:00', close: '22:00' },
      wednesday: { open: '07:00', close: '22:00' },
      thursday: { open: '07:00', close: '22:00' },
      friday: { open: '07:00', close: '23:00' },
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '09:00', close: '21:00' },
    },
    status: 'APPROVED',
    images: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockOffers: Offer[] = [
  {
    id: '1',
    partner_id: '1',
    category: 'BAKERY',
    title: 'Fresh Khachapuri - Evening Special',
    description: 'Traditional Georgian cheese bread, freshly baked this afternoon. Perfect for dinner!',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
    original_price: 12.0,
    smart_price: 8.0,
    quantity_available: 5,
    quantity_total: 10,
    pickup_window: {
      start: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2 hours from now
      end: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(), // 4 hours from now
    },
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    partner: mockPartners[0],
  },
  {
    id: '2',
    partner_id: '1',
    category: 'BAKERY',
    title: 'Chocolate Croissants',
    description: 'Buttery croissants filled with premium dark chocolate',
    images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800'],
    original_price: 6.0,
    smart_price: 4.0,
    quantity_available: 8,
    quantity_total: 12,
    pickup_window: {
      start: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    },
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    partner: mockPartners[0],
  },
  {
    id: '3',
    partner_id: '2',
    category: 'CAFE',
    title: 'Specialty Coffee & Cake Combo',
    description: 'Your choice of specialty coffee with a slice of our homemade cake',
    images: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
    original_price: 15.0,
    smart_price: 10.0,
    quantity_available: 6,
    quantity_total: 10,
    pickup_window: {
      start: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    },
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    partner: mockPartners[1],
  },
  {
    id: '4',
    partner_id: '2',
    category: 'CAFE',
    title: 'Fresh Pastry Selection',
    description: 'Assorted pastries baked fresh this morning',
    images: ['https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=800'],
    original_price: 10.0,
    smart_price: 7.0,
    quantity_available: 4,
    quantity_total: 8,
    pickup_window: {
      start: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    },
    status: 'ACTIVE',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    partner: mockPartners[1],
  },
];